### ISSUE TITLE
No such file or directory: './models/gmflow_sintel-0c07dcb3.pth'

### ISSUE THREAD

**Issue by le0815** [gustavorayo/video-to-cartoon#1]
Hello, I am attempting to install this project on Kaggle by:
`git clone --recursive git@github.com:gustavorayo/video-to-cartoon.git`
After running line: 
`!cd /kaggle/working/video-to-cartoon && python vid2cartoon.py --input_video <your_input_video> --style ghibli --output /kaggle/working/test.mp4`
I have got error as the title of this issues.
Full log of error:
```
2024-08-13 04:48:47.581186: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-13 04:48:47.581248: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-13 04:48:47.582838: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Number of frames: 256
Time taken by video_to_frames: 3.600996 seconds
Time taken by __init__: 0.000005 seconds
model and style nitrosocke/Ghibli-Diffusion ghibli style
Loading pipeline components...: 100%|█████████████| 6/6 [00:02<00:00,  2.98it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.controlnet.pipeline_controlnet_img2img.StableDiffusionControlNetImg2ImgPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Time taken by load: 4.991731 seconds
Loading clip
Loading BLIP model...
load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth
Loading CLIP model...
Loaded CLIP model and data in 10.44 seconds.
Time taken by generate_key_frames: 0.000054 seconds
Time taken by get_ebsynth: 0.000025 seconds
cd deps/Rerender_A_Video && python video_blend.py /kaggle/working/video-to-cartoon/tmp --end 256 --itv 85 --key keys --output /kaggle/working/test.mp4 --fps 30 --n_proc 4
 Traceback (most recent call last):
  File "/kaggle/working/video-to-cartoon/deps/Rerender_A_Video/video_blend.py", line 15, in <module>
    from blender.guide import (BaseGuide, ColorGuide, EdgeGuide, PositionalGuide,
  File "/kaggle/working/video-to-cartoon/deps/Rerender_A_Video/blender/guide.py", line 6, in <module>
    from flow.flow_utils import flow_calc, read_flow, read_mask
  File "/kaggle/working/video-to-cartoon/deps/Rerender_A_Video/flow/flow_utils.py", line 258, in <module>
    flow_calc = FlowCalc()
  File "/kaggle/working/video-to-cartoon/deps/Rerender_A_Video/flow/flow_utils.py", line 156, in __init__
    checkpoint = torch.load(model_path,
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/gmflow_sintel-0c07dcb3.pth'

Time taken by advanced_propagation: 3.178061 seconds
```
Anyone like same to me?
Thank you, have a nice day!

**Comment by le0815** [comment]
I've solved by download pretrains model: `https://drive.google.com/file/d/1d5C5cgHIxWGsFR1vYs5XrQbbUiZl9TX2/edit`
And copy the model named in the error log to `models` file.

**Comment by ranjitsingha** [comment]
> I've solved by download pretrains model: `https://drive.google.com/file/d/1d5C5cgHIxWGsFR1vYs5XrQbbUiZl9TX2/edit` And copy the model named in the error log to `models` file.

Where is the model file folder located?

**Comment by gustavorayo** [comment]
Dear [ranjitsingha](https://github.com/ranjitsingha)
The models are located at: ./deps/Rerender_A_Video/models
The install.py script downloads it. Please make sure to execute it.

`python install.py`
