### ISSUE TITLE
FileNotFoundError: No such file or directory: './models/gmflow_sintel-0c07dcb3.pth'

### ISSUE THREAD

**Issue by ranjitsingha** [gustavorayo/video-to-cartoon#5]
`Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(model_path,
Traceback (most recent call last):
  File "/content/video-to-cartoon/deps/Rerender_A_Video/video_blend.py", line 15, in <module>
    from blender.guide import (BaseGuide, ColorGuide, EdgeGuide, PositionalGuide,
  File "/content/video-to-cartoon/deps/Rerender_A_Video/blender/guide.py", line 6, in <module>
    from flow.flow_utils import flow_calc, read_flow, read_mask
  File "/content/video-to-cartoon/deps/Rerender_A_Video/flow/flow_utils.py", line 258, in <module>
    flow_calc = FlowCalc()
  File "/content/video-to-cartoon/deps/Rerender_A_Video/flow/flow_utils.py", line 156, in __init__
    checkpoint = torch.load(model_path,
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/gmflow_sintel-0c07dcb3.pth'

Time taken by advanced_propagation: 6.629140 seconds
`

**Comment by gustavorayo** [comment]
Dear [ranjitsingha](https://github.com/ranjitsingha)
It seems you are missing the gmflow_sintel-0c07dcb3.pth model.
Please make sure to execute the install.py script
`python install.py`
